update index.js
修正当 controller 中存在不注解方法时 报错问题：
\ts-egg-guide\node_modules\egg-shell-decorators\index.js:47
        router[reqMethod](prefix + path, ...middlewares, routerCb);
                                                         ^
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at Object.EggShell (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg-shell-decorators\index.js:47:58)
    at exports.default (D:\个人项目练习\ts-egg\ts-egg-guide\app\router.ts:7:3)
    at AppWorkerLoader.loadFile (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg-core\lib\loader\egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg-core\lib\loader\mixin\router.js:16:10)
    at AppWorkerLoader.app.loader.loadRouter (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg-router-plus\app.js:31:16)
    at AppWorkerLoader.load (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg\lib\loader\app_worker_loader.js:43:10)
    at new Application (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (D:\个人项目练习\ts-egg\ts-egg-guide\node_modules\egg-cluster\lib\app_worker.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Waiting for the debugger to disconnect...